% Auto-generated MATLAB data file
% Source ODB : C:/temp/lfrp_cf25_20p.odb
% Step       : Step-1
% Generated by data_extractor.py (run_computation)
% 
% Every '%' line in this file is a comment/context note only.
% Every other line is a real MATLAB assignment -- run or open
% this file in MATLAB and each named variable below becomes
% directly available in the workspace.

% Phase volume fractions (at first nonzero frame):
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
VF_phase1 = 7.500171e-01;
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
VF_phase2 = 2.499829e-01;

% [S] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [26170088.0368966, 45853594.5945389, 24309107.2691666, 27882200.0280826, -0.000762047266202554, 26904789.3655475]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [26225368.4192031, 42168192.7140457, 26331520.7972106, 22543961.8191868, -33066.6043055626, 22599714.5624303]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [26004231.7235719, 56910811.3415216, 18241311.8273789, 43898379.2228704, 99208.8818302276, 39821194.8902747]]

% [E] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-5.09431648523496e-12, 0.00499999999417478, -4.4495835428705e-11, 0.00707106778064825, -9.68809029342331e-06, 0.00707106780999296]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-4.32415528626444e-05, 0.00645111481196111, -7.00852701809693e-11, 0.00918334915448149, -1.34697783694408e-05, 0.0092060601983264]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.00012973650171113, 0.000646257421363527, 3.22794893971172e-11, 0.000733644145871378, 1.65801145665514e-06, 0.000665504900853133]]

% [CENER] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [DMENER] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [EE] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-5.09431648523496e-12, 0.00499999999417478, -4.4495835428705e-11, 0.00707106778064825, -9.68809029342331e-06, 0.00707106780999296]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [-4.32415528626444e-05, 0.00645111481196111, -7.00852701809693e-11, 0.00918334915448149, -1.34697783694408e-05, 0.0092060601983264]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.00012973650171113, 0.000646257421363527, 3.22794893971172e-11, 0.000733644145871378, 1.65801145665514e-06, 0.000665504900853133]]

% [EENER] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELASE] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELCD] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELCTE] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELDMD] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELJD] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELKE] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELPD] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELSD] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [ELSE] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [1.67200935463291]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [2.06067545704102]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.309113483798607]]

% [ELVD] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [IE] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

% [IVOL] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[1.60698502338764e-06], [1.60698502338764e-06]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[1.52341801717476e-06], [1.52341801717476e-06]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[1.85770896898583e-06], [1.85770896898583e-06]]

% [JENER] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [PENER] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]

% [SENER] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [308335.245099706]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [394239.415646766]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [50599.1652881065]]

% [THE] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

% [U] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0, 0.0, 0.0], [0.00258516496757293, 0.00525343135154424, 0.00251330665287406]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0, 0.0, 0.0], [0.00258378075100196, 0.00525313092013305, 0.00251325009497355]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0, 0.0, 0.0], [0.00255126851841977, 0.0052398812919701, 0.00247707799581319]]

% [VENER] overall (volume/area/count-weighted) -- summary only
%   t=[0.0, 1.0]
%   overall=[[0.0], [0.0]]
%   phase 1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX): [[0.0], [0.0]]
%   phase 2 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION): [[0.0], [0.0]]



% 
% ===== MATLAB Variable Assignments =====
% Tensor notations included: Full tensor (matrix) for tensor quantities, Mandel (single column) for tensor quantities, Voigt (single column) for tensor quantities
% Scalars are written as 'name = value;'.
% Non-tensor vectors are written as 'name = [ ...column... ];'.
% 
% ---- S ----
% S(frame 0, t=0.0):
% S_overall_frame0_t0 (tensor matrix):
  S_overall_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  S_overall_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  S_overall_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% S_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  S_phase1_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  S_phase1_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  S_phase1_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% S_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  S_phase2_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  S_phase2_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  S_phase2_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% S(frame 1, t=1.0):
% S_overall_frame1_t1 (tensor matrix):
  S_overall_frame1_t1_full = [   % complete 3x3 matrix
    2.617009e+07   1.902456e+07   -5.388488e-04
    1.902456e+07   4.585359e+07   1.971569e+07
    -5.388488e-04   1.971569e+07   2.430911e+07 ];
  S_overall_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 2.617009e+07
      4.585359e+07
      2.430911e+07
      2.788220e+07
      -7.620473e-04
      2.690479e+07 ];
  S_overall_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 2.617009e+07
      4.585359e+07
      2.430911e+07
      1.902456e+07
      -5.388488e-04
      1.971569e+07 ];
% S_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  S_phase1_frame1_t1_full = [   % complete 3x3 matrix
    2.622537e+07   1.598041e+07   -2.338162e+04
    1.598041e+07   4.216819e+07   1.594099e+07
    -2.338162e+04   1.594099e+07   2.633152e+07 ];
  S_phase1_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 2.622537e+07
      4.216819e+07
      2.633152e+07
      2.254396e+07
      -3.306660e+04
      2.259971e+07 ];
  S_phase1_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 2.622537e+07
      4.216819e+07
      2.633152e+07
      1.598041e+07
      -2.338162e+04
      1.594099e+07 ];
% S_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  S_phase2_frame1_t1_full = [   % complete 3x3 matrix
    2.600423e+07   2.815784e+07   7.015127e+04
    2.815784e+07   5.691081e+07   3.104084e+07
    7.015127e+04   3.104084e+07   1.824131e+07 ];
  S_phase2_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 2.600423e+07
      5.691081e+07
      1.824131e+07
      4.389838e+07
      9.920888e+04
      3.982119e+07 ];
  S_phase2_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 2.600423e+07
      5.691081e+07
      1.824131e+07
      2.815784e+07
      7.015127e+04
      3.104084e+07 ];

% 
% ---- E ----
% E(frame 0, t=0.0):
% E_overall_frame0_t0 (tensor matrix):
  E_overall_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  E_overall_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  E_overall_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% E_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  E_phase1_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  E_phase1_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  E_phase1_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% E_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  E_phase2_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  E_phase2_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  E_phase2_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% E(frame 1, t=1.0):
% E_overall_frame1_t1 (tensor matrix):
  E_overall_frame1_t1_full = [   % complete 3x3 matrix
    -5.094316e-12   1.000000e-02   -1.370103e-05
    1.000000e-02   5.000000e-03   1.000000e-02
    -1.370103e-05   1.000000e-02   -4.449584e-11 ];
  E_overall_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ -5.094316e-12
      5.000000e-03
      -4.449584e-11
      7.071068e-03
      -9.688090e-06
      7.071068e-03 ];
  E_overall_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ -5.094316e-12
      5.000000e-03
      -4.449584e-11
      1.000000e-02
      -1.370103e-05
      1.000000e-02 ];
% E_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  E_phase1_frame1_t1_full = [   % complete 3x3 matrix
    -4.324155e-05   1.301934e-02   -1.904914e-05
    1.301934e-02   6.451115e-03   1.298722e-02
    -1.904914e-05   1.298722e-02   -7.008527e-11 ];
  E_phase1_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ -4.324155e-05
      6.451115e-03
      -7.008527e-11
      9.183349e-03
      -1.346978e-05
      9.206060e-03 ];
  E_phase1_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ -4.324155e-05
      6.451115e-03
      -7.008527e-11
      1.301934e-02
      -1.904914e-05
      1.298722e-02 ];
% E_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  E_phase2_frame1_t1_full = [   % complete 3x3 matrix
    1.297365e-04   9.411661e-04   2.344782e-06
    9.411661e-04   6.462574e-04   1.037530e-03
    2.344782e-06   1.037530e-03   3.227949e-11 ];
  E_phase2_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 1.297365e-04
      6.462574e-04
      3.227949e-11
      7.336441e-04
      1.658011e-06
      6.655049e-04 ];
  E_phase2_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 1.297365e-04
      6.462574e-04
      3.227949e-11
      9.411661e-04
      2.344782e-06
      1.037530e-03 ];

% 
% ---- CENER ----
% CENER(frame 0, t=0.0):
CENER_overall_frame0_t0 = 0.000000e+00;
% CENER_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
CENER_phase1_frame0_t0 = 0.000000e+00;
% CENER_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
CENER_phase2_frame0_t0 = 0.000000e+00;

% CENER(frame 1, t=1.0):
CENER_overall_frame1_t1 = 0.000000e+00;
% CENER_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
CENER_phase1_frame1_t1 = 0.000000e+00;
% CENER_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
CENER_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- DMENER ----
% DMENER(frame 0, t=0.0):
DMENER_overall_frame0_t0 = 0.000000e+00;
% DMENER_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
DMENER_phase1_frame0_t0 = 0.000000e+00;
% DMENER_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
DMENER_phase2_frame0_t0 = 0.000000e+00;

% DMENER(frame 1, t=1.0):
DMENER_overall_frame1_t1 = 0.000000e+00;
% DMENER_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
DMENER_phase1_frame1_t1 = 0.000000e+00;
% DMENER_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
DMENER_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- EE ----
% EE(frame 0, t=0.0):
% EE_overall_frame0_t0 (tensor matrix):
  EE_overall_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  EE_overall_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  EE_overall_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% EE_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  EE_phase1_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  EE_phase1_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  EE_phase1_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% EE_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  EE_phase2_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  EE_phase2_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  EE_phase2_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% EE(frame 1, t=1.0):
% EE_overall_frame1_t1 (tensor matrix):
  EE_overall_frame1_t1_full = [   % complete 3x3 matrix
    -5.094316e-12   1.000000e-02   -1.370103e-05
    1.000000e-02   5.000000e-03   1.000000e-02
    -1.370103e-05   1.000000e-02   -4.449584e-11 ];
  EE_overall_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ -5.094316e-12
      5.000000e-03
      -4.449584e-11
      7.071068e-03
      -9.688090e-06
      7.071068e-03 ];
  EE_overall_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ -5.094316e-12
      5.000000e-03
      -4.449584e-11
      1.000000e-02
      -1.370103e-05
      1.000000e-02 ];
% EE_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  EE_phase1_frame1_t1_full = [   % complete 3x3 matrix
    -4.324155e-05   1.301934e-02   -1.904914e-05
    1.301934e-02   6.451115e-03   1.298722e-02
    -1.904914e-05   1.298722e-02   -7.008527e-11 ];
  EE_phase1_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ -4.324155e-05
      6.451115e-03
      -7.008527e-11
      9.183349e-03
      -1.346978e-05
      9.206060e-03 ];
  EE_phase1_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ -4.324155e-05
      6.451115e-03
      -7.008527e-11
      1.301934e-02
      -1.904914e-05
      1.298722e-02 ];
% EE_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  EE_phase2_frame1_t1_full = [   % complete 3x3 matrix
    1.297365e-04   9.411661e-04   2.344782e-06
    9.411661e-04   6.462574e-04   1.037530e-03
    2.344782e-06   1.037530e-03   3.227949e-11 ];
  EE_phase2_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 1.297365e-04
      6.462574e-04
      3.227949e-11
      7.336441e-04
      1.658011e-06
      6.655049e-04 ];
  EE_phase2_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 1.297365e-04
      6.462574e-04
      3.227949e-11
      9.411661e-04
      2.344782e-06
      1.037530e-03 ];

% 
% ---- EENER ----
% EENER(frame 0, t=0.0):
EENER_overall_frame0_t0 = 0.000000e+00;
% EENER_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
EENER_phase1_frame0_t0 = 0.000000e+00;
% EENER_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
EENER_phase2_frame0_t0 = 0.000000e+00;

% EENER(frame 1, t=1.0):
EENER_overall_frame1_t1 = 0.000000e+00;
% EENER_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
EENER_phase1_frame1_t1 = 0.000000e+00;
% EENER_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
EENER_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELASE ----
% ELASE(frame 0, t=0.0):
ELASE_overall_frame0_t0 = 0.000000e+00;
% ELASE_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELASE_phase1_frame0_t0 = 0.000000e+00;
% ELASE_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELASE_phase2_frame0_t0 = 0.000000e+00;

% ELASE(frame 1, t=1.0):
ELASE_overall_frame1_t1 = 0.000000e+00;
% ELASE_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELASE_phase1_frame1_t1 = 0.000000e+00;
% ELASE_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELASE_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELCD ----
% ELCD(frame 0, t=0.0):
ELCD_overall_frame0_t0 = 0.000000e+00;
% ELCD_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELCD_phase1_frame0_t0 = 0.000000e+00;
% ELCD_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELCD_phase2_frame0_t0 = 0.000000e+00;

% ELCD(frame 1, t=1.0):
ELCD_overall_frame1_t1 = 0.000000e+00;
% ELCD_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELCD_phase1_frame1_t1 = 0.000000e+00;
% ELCD_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELCD_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELCTE ----
% ELCTE(frame 0, t=0.0):
ELCTE_overall_frame0_t0 = 0.000000e+00;
% ELCTE_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELCTE_phase1_frame0_t0 = 0.000000e+00;
% ELCTE_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELCTE_phase2_frame0_t0 = 0.000000e+00;

% ELCTE(frame 1, t=1.0):
ELCTE_overall_frame1_t1 = 0.000000e+00;
% ELCTE_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELCTE_phase1_frame1_t1 = 0.000000e+00;
% ELCTE_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELCTE_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELDMD ----
% ELDMD(frame 0, t=0.0):
ELDMD_overall_frame0_t0 = 0.000000e+00;
% ELDMD_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELDMD_phase1_frame0_t0 = 0.000000e+00;
% ELDMD_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELDMD_phase2_frame0_t0 = 0.000000e+00;

% ELDMD(frame 1, t=1.0):
ELDMD_overall_frame1_t1 = 0.000000e+00;
% ELDMD_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELDMD_phase1_frame1_t1 = 0.000000e+00;
% ELDMD_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELDMD_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELJD ----
% ELJD(frame 0, t=0.0):
ELJD_overall_frame0_t0 = 0.000000e+00;
% ELJD_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELJD_phase1_frame0_t0 = 0.000000e+00;
% ELJD_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELJD_phase2_frame0_t0 = 0.000000e+00;

% ELJD(frame 1, t=1.0):
ELJD_overall_frame1_t1 = 0.000000e+00;
% ELJD_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELJD_phase1_frame1_t1 = 0.000000e+00;
% ELJD_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELJD_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELKE ----
% ELKE(frame 0, t=0.0):
ELKE_overall_frame0_t0 = 0.000000e+00;
% ELKE_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELKE_phase1_frame0_t0 = 0.000000e+00;
% ELKE_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELKE_phase2_frame0_t0 = 0.000000e+00;

% ELKE(frame 1, t=1.0):
ELKE_overall_frame1_t1 = 0.000000e+00;
% ELKE_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELKE_phase1_frame1_t1 = 0.000000e+00;
% ELKE_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELKE_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELPD ----
% ELPD(frame 0, t=0.0):
ELPD_overall_frame0_t0 = 0.000000e+00;
% ELPD_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELPD_phase1_frame0_t0 = 0.000000e+00;
% ELPD_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELPD_phase2_frame0_t0 = 0.000000e+00;

% ELPD(frame 1, t=1.0):
ELPD_overall_frame1_t1 = 0.000000e+00;
% ELPD_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELPD_phase1_frame1_t1 = 0.000000e+00;
% ELPD_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELPD_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELSD ----
% ELSD(frame 0, t=0.0):
ELSD_overall_frame0_t0 = 0.000000e+00;
% ELSD_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELSD_phase1_frame0_t0 = 0.000000e+00;
% ELSD_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELSD_phase2_frame0_t0 = 0.000000e+00;

% ELSD(frame 1, t=1.0):
ELSD_overall_frame1_t1 = 0.000000e+00;
% ELSD_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELSD_phase1_frame1_t1 = 0.000000e+00;
% ELSD_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELSD_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- ELSE ----
% ELSE(frame 0, t=0.0):
ELSE_overall_frame0_t0 = 0.000000e+00;
% ELSE_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELSE_phase1_frame0_t0 = 0.000000e+00;
% ELSE_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELSE_phase2_frame0_t0 = 0.000000e+00;

% ELSE(frame 1, t=1.0):
ELSE_overall_frame1_t1 = 1.672009e+00;
% ELSE_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELSE_phase1_frame1_t1 = 2.060675e+00;
% ELSE_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELSE_phase2_frame1_t1 = 3.091135e-01;

% 
% ---- ELVD ----
% ELVD(frame 0, t=0.0):
ELVD_overall_frame0_t0 = 0.000000e+00;
% ELVD_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELVD_phase1_frame0_t0 = 0.000000e+00;
% ELVD_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELVD_phase2_frame0_t0 = 0.000000e+00;

% ELVD(frame 1, t=1.0):
ELVD_overall_frame1_t1 = 0.000000e+00;
% ELVD_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
ELVD_phase1_frame1_t1 = 0.000000e+00;
% ELVD_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
ELVD_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- IE ----
% IE(frame 0, t=0.0):
% IE_overall_frame0_t0 (tensor matrix):
  IE_overall_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  IE_overall_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  IE_overall_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% IE_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  IE_phase1_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  IE_phase1_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  IE_phase1_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% IE_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  IE_phase2_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  IE_phase2_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  IE_phase2_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% IE(frame 1, t=1.0):
% IE_overall_frame1_t1 (tensor matrix):
  IE_overall_frame1_t1_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  IE_overall_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  IE_overall_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% IE_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  IE_phase1_frame1_t1_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  IE_phase1_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  IE_phase1_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% IE_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  IE_phase2_frame1_t1_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  IE_phase2_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  IE_phase2_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% 
% ---- IVOL ----
% IVOL(frame 0, t=0.0):
IVOL_overall_frame0_t0 = 1.606985e-06;
% IVOL_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
IVOL_phase1_frame0_t0 = 1.523418e-06;
% IVOL_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
IVOL_phase2_frame0_t0 = 1.857709e-06;

% IVOL(frame 1, t=1.0):
IVOL_overall_frame1_t1 = 1.606985e-06;
% IVOL_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
IVOL_phase1_frame1_t1 = 1.523418e-06;
% IVOL_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
IVOL_phase2_frame1_t1 = 1.857709e-06;

% 
% ---- JENER ----
% JENER(frame 0, t=0.0):
JENER_overall_frame0_t0 = 0.000000e+00;
% JENER_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
JENER_phase1_frame0_t0 = 0.000000e+00;
% JENER_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
JENER_phase2_frame0_t0 = 0.000000e+00;

% JENER(frame 1, t=1.0):
JENER_overall_frame1_t1 = 0.000000e+00;
% JENER_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
JENER_phase1_frame1_t1 = 0.000000e+00;
% JENER_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
JENER_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- PENER ----
% PENER(frame 0, t=0.0):
PENER_overall_frame0_t0 = 0.000000e+00;
% PENER_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
PENER_phase1_frame0_t0 = 0.000000e+00;
% PENER_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
PENER_phase2_frame0_t0 = 0.000000e+00;

% PENER(frame 1, t=1.0):
PENER_overall_frame1_t1 = 0.000000e+00;
% PENER_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
PENER_phase1_frame1_t1 = 0.000000e+00;
% PENER_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
PENER_phase2_frame1_t1 = 0.000000e+00;

% 
% ---- SENER ----
% SENER(frame 0, t=0.0):
SENER_overall_frame0_t0 = 0.000000e+00;
% SENER_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
SENER_phase1_frame0_t0 = 0.000000e+00;
% SENER_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
SENER_phase2_frame0_t0 = 0.000000e+00;

% SENER(frame 1, t=1.0):
SENER_overall_frame1_t1 = 3.083352e+05;
% SENER_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
SENER_phase1_frame1_t1 = 3.942394e+05;
% SENER_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
SENER_phase2_frame1_t1 = 5.059917e+04;

% 
% ---- THE ----
% THE(frame 0, t=0.0):
% THE_overall_frame0_t0 (tensor matrix):
  THE_overall_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  THE_overall_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  THE_overall_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% THE_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  THE_phase1_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  THE_phase1_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  THE_phase1_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% THE_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  THE_phase2_frame0_t0_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  THE_phase2_frame0_t0_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  THE_phase2_frame0_t0_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% THE(frame 1, t=1.0):
% THE_overall_frame1_t1 (tensor matrix):
  THE_overall_frame1_t1_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  THE_overall_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  THE_overall_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% THE_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX):
  THE_phase1_frame1_t1_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  THE_phase1_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  THE_phase1_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% THE_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION):
  THE_phase2_frame1_t1_full = [   % complete 3x3 matrix
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00
    0.000000e+00   0.000000e+00   0.000000e+00 ];
  THE_phase2_frame1_t1_mandel = ...   % single column, order 11,22,33,23,13,12
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];
  THE_phase2_frame1_t1_voigt = ...   % single column, order 11,22,33,12,13,23
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% 
% ---- U ----
% U(frame 0, t=0.0):
% U_overall_frame0_t0 (vector, 3 components)
U_overall_frame0_t0 = ...
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% U_phase1_frame0_t0 (vector, 3 components, UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
U_phase1_frame0_t0 = ...
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00 ];
% U_phase2_frame0_t0 (vector, 3 components, UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
U_phase2_frame0_t0 = ...
    [ 0.000000e+00
      0.000000e+00
      0.000000e+00 ];

% U(frame 1, t=1.0):
% U_overall_frame1_t1 (vector, 3 components)
U_overall_frame1_t1 = ...
    [ 2.585165e-03
      5.253431e-03
      2.513307e-03 ];
% U_phase1_frame1_t1 (vector, 3 components, UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
U_phase1_frame1_t1 = ...
    [ 2.583781e-03
      5.253131e-03
      2.513250e-03 ];
% U_phase2_frame1_t1 (vector, 3 components, UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
U_phase2_frame1_t1 = ...
    [ 2.551269e-03
      5.239881e-03
      2.477078e-03 ];

% 
% ---- VENER ----
% VENER(frame 0, t=0.0):
VENER_overall_frame0_t0 = 0.000000e+00;
% VENER_phase1_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
VENER_phase1_frame0_t0 = 0.000000e+00;
% VENER_phase2_frame0_t0 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
VENER_phase2_frame0_t0 = 0.000000e+00;

% VENER(frame 1, t=1.0):
VENER_overall_frame1_t1 = 0.000000e+00;
% VENER_phase1_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART1 / MATRIX)
VENER_phase1_frame1_t1 = 0.000000e+00;
% VENER_phase2_frame1_t1 (UNITCELL-1 / Section-ASSEMBLY_UNITCELL-1_PART2 / INCLUSION)
VENER_phase2_frame1_t1 = 0.000000e+00;

% processing duration 17.9309999943 Seconds
